### ISSUE TITLE
rhsso73 ImageStream may not exist in a cluster

### ISSUE THREAD

**Issue by aidenkeating** [NAPS-emergency-response-project/install#10]
In the current installation it seems to expect the ImageStream `redhat-sso73-openshift` to exist. However this doesn't seem to always be the case.

On an Integreatly cluster from `master` this ImageStream doesn't exist.

In the current long-running cluster, there appears to be an ImageStream setup for 7.3. We could implement this in the SSO setup to ensure it's available.

@btison I'm happy to work on this, just adding this for visibility and to ensure it makes sense? I noticed the issue when trying an install on top of an Integreatly install from `master` from the Demo System.

**Comment by StevenTobin** [comment]
I've also hit an issue where two openjdk18 images are required for the jenkins pipeline builds but are not available in the cluster by default. registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift 1.5 and 1.6
