### ISSUE TITLE
installation error when running on ocp-workshop cluster

### ISSUE THREAD

**Issue by sshaaf** [NAPS-emergency-response-project/install#11]
TASK [openshift_sso : install theme-buildconfig] ********************************************************
changed: [localhost]

TASK [openshift_sso : copy theme imagestream template to work directory] ********************************
changed: [localhost]

TASK [openshift_sso : install theme-buildconfig image stream] *******************************************
changed: [localhost]

TASK [openshift_sso : check if sso is deployed] *********************************************************
ok: [localhost]

TASK [openshift_sso : deploy sso] ***********************************************************************
changed: [localhost]
ansible-playbook playbooks/install.yml

TASK [openshift_sso : wait for rhsso to be ready] *******************************************************
FAILED - RETRYING: wait for rhsso to be ready (10 retries left).
FAILED - RETRYING: wait for rhsso to be ready (9 retries left).
FAILED - RETRYING: wait for rhsso to be ready (8 retries left).
FAILED - RETRYING: wait for rhsso to be ready (7 retries left).
FAILED - RETRYING: wait for rhsso to be ready (6 retries left).
FAILED - RETRYING: wait for rhsso to be ready (5 retries left).
FAILED - RETRYING: wait for rhsso to be ready (4 retries left).
FAILED - RETRYING: wait for rhsso to be ready (3 retries left).
FAILED - RETRYING: wait for rhsso to be ready (2 retries left).
FAILED - RETRYING: wait for rhsso to be ready (1 retries left).
fatal: [localhost]: FAILED! => {"attempts": 10, "changed": false, "cmd": "oc get dc sso -o template --template=\\{\\{.status.readyReplicas\\}\\} -n naps-emergency-response", "delta": "0:00:01.051210", "end": "2019-04-15 15:37:11.142708", "rc": 0, "start": "2019-04-15 15:37:10.091498", "stderr": "", "stderr_lines": [], "stdout": "<no value>", "stdout_lines": ["<no value>"]}

NO MORE HOSTS LEFT **************************************************************************************

PLAY RECAP **********************************************************************************************
localhost                  : ok=146  changed=67   unreachable=0    failed=1

**Comment by btison** [comment]
This has probably to do with the fact that on a ocp-workshop cluster the sso 7.3 imagestream is not installed by default. Installing imagestreams is not yet covered by the playbook.

**Comment by sshaaf** [comment]
Yep installing the image streams fixed the issue:
for resource in sso73-image-stream.json   sso73-https.json   sso73-mysql.json   sso73-mysql-persistent.json   sso73-postgresql.json   sso73-postgresql-persistent.json   sso73-x509-https.json   sso73-x509-mysql-persistent.json   sso73-x509-postgresql-persistent.json; do   oc replace -n openshift --force -f   https://raw.githubusercontent.com/jboss-container-images/redhat-sso-7-openshift-image/sso73-dev/templates/${resource}; done
oc -n openshift import-image redhat-sso73-openshift:1.0
