### ISSUE TITLE
Ansible error while installing the httpd

### ISSUE THREAD

**Issue by nagarajpala** [NAPS-emergency-response-project/install#4]
When I tried to install the httpd package it is showing as below error.

#ansible-playbook install.yml
[WARNING]: provided hosts list is empty, only localhost is available. Note
that the implicit localhost does not match 'all'

*************************
as mentioned in script:
hosts: webserver.local
*************************

Can you please help on this issue...

**Comment by btison** [comment]
wrong repo??
