### ISSUE TITLE
TASK [openshift_sso : copy realm template]

### ISSUE THREAD

**Issue by sshaaf** [NAPS-emergency-response-project/install#48]
Running uninstall fails
> ansible-playbook playbooks/install.yml -e ACTION=uninstall
> fatal: [localhost]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'ocp_domain' is undefined"}

**Comment by sshaaf** [comment]
@btison

**Comment by btison** [comment]
Fixed with commit 4c72ecb
