### ISSUE TITLE
Indicate the post-installation cluster admin user id and password, replacing opentlc-mgr

### ISSUE THREAD

**Issue by honghuac** [NAPS-emergency-response-project/install#73]
No where on the [readme.adoc](https://github.com/Emergency-Response-Demo/install/blob/master/ansible/README.md) are these information made available: https://github.com/Emergency-Response-Demo/install/blob/master/ansible/README.md

**Comment by btison** [comment]
The installation playbook does not change the OCP cluster admin user id and password.
