### ISSUE TITLE
responder client app tag missing

### ISSUE THREAD

**Issue by sshaaf** [NAPS-emergency-response-project/install#89]
on this page, there is no 2.3 tag, however in the installer we are calling for it

https://quay.io/repository/emergencyresponsedemo/emergency-response-client-app?tag=latest&tab=tags

**Comment by sshaaf** [comment]
@jbride @btison

**Comment by jbride** [comment]
Thanks Shaaf.
Good point.
I've added the 2.3 tag for this container image in quay.
I'll make sure going forward that new tags are created for this image for subsequent releases.

**Comment by sshaaf** [comment]
thanks!
